def create_page_load_tests(agent_list):
    tests = [
            {
            "interval": 900,
            "bgpMeasurements": True,
            "usePublicBgp": True,
            "httpInterval": 900,
            "liveShare": False,
            "testName": "drive.google.com - Page Load11",
            "savedEvent": False,
            "type": "page-load",
            "alertsEnabled": True,
            "enabled": True,
            "url": "https://drive.google.com",
            "authType": "none",
            "bandwidthMeasurements": False,
            "httpTargetTime": 1000,
            "httpTimeLimit": 5,
            "httpVersion": 2,
            "includeHeaders": True,
            "mtuMeasurements": True,
            "numPathTraces": 3,
            "pathTraceMode": "classic",
            "probeMode": "auto",
            "networkMeasurements": True,
            "protocol": "tcp",
            "sslVersionId": "0",
            "useNtlm": False,
            "verifyCertificate": True,
            "allowUnsafeLegacyRenegotiation": True,
            "overrideAgentProxy": False,
            "distributedTracing": False,
            "allowGeolocation": False,
            "allowMicAndCamera": False,
            "blockDomains": "",
            "browserLanguage": "en-US",
            "disableScreenshot": False,
            "pageLoadingStrategy": "normal",
            "contentRegex": "",
            "emulatedDeviceId": "281474976710656",
            "followRedirects": True,
            "pageLoadTargetTime": 6,
            "pageLoadTimeLimit": 10,
            "randomizedStartTime": False,
            "sslVersion": "Auto",
            "agents": [{"agentId": "4739"}]
        },
        {
            "interval": 900,
            "bgpMeasurements": True,
            "usePublicBgp": True,
            "httpInterval": 900,
            "liveShare": False,
            "testName": "elisa.fi - Page Load11",
            "savedEvent": False,
            "type": "page-load",
            "alertsEnabled": True,
            "enabled": True,
            "url": "https://elisa.fi",
            "authType": "none",
            "bandwidthMeasurements": False,
            "httpTargetTime": 1000,
            "httpTimeLimit": 5,
            "httpVersion": 2,
            "includeHeaders": True,
            "mtuMeasurements": True,
            "numPathTraces": 3,
            "pathTraceMode": "classic",
            "probeMode": "auto",
            "networkMeasurements": True,
            "protocol": "tcp",
            "sslVersionId": "0",
            "useNtlm": False,
            "verifyCertificate": True,
            "allowUnsafeLegacyRenegotiation": True,
            "overrideAgentProxy": False,
            "distributedTracing": False,
            "allowGeolocation": False,
            "allowMicAndCamera": False,
            "blockDomains": "",
            "browserLanguage": "en-US",
            "disableScreenshot": False,
            "pageLoadingStrategy": "normal",
            "contentRegex": "",
            "emulatedDeviceId": "281474976710656",
            "followRedirects": True,
            "pageLoadTargetTime": 6,
            "pageLoadTimeLimit": 10,
            "randomizedStartTime": False,
            "sslVersion": "Auto",
            "agents": [{"agentId": "4739"}]
        },
        {
            "interval": 900,
            "bgpMeasurements": True,
            "usePublicBgp": True,
            "httpInterval": 900,
            "liveShare": False,
            "testName": "GMail Basic Mail11",
            "savedEvent": False,
            "type": "page-load",
            "alertsEnabled": True,
            "enabled": True,
            "url": "https://mail.google.com",
            "authType": "none",
            "bandwidthMeasurements": False,
            "httpTargetTime": 1000,
            "httpTimeLimit": 5,
            "httpVersion": 2,
            "includeHeaders": True,
            "mtuMeasurements": True,
            "numPathTraces": 3,
            "pathTraceMode": "classic",
            "probeMode": "auto",
            "networkMeasurements": True,
            "protocol": "tcp",
            "sslVersionId": "0",
            "useNtlm": False,
            "verifyCertificate": True,
            "allowUnsafeLegacyRenegotiation": True,
            "overrideAgentProxy": False,
            "distributedTracing": False,
            "allowGeolocation": False,
            "allowMicAndCamera": False,
            "blockDomains": "",
            "browserLanguage": "en-US",
            "disableScreenshot": False,
            "pageLoadingStrategy": "normal",
            "contentRegex": "",
            "emulatedDeviceId": "281474976710656",
            "followRedirects": True,
            "pageLoadTargetTime": 6,
            "pageLoadTimeLimit": 10,
            "randomizedStartTime": False,
            "sslVersion": "Auto",
           "agents": [{"agentId": "4739"}]
        },
        {
            "interval": 900,
            "bgpMeasurements": True,
            "usePublicBgp": True,
            "httpInterval": 900,
            "liveShare": False,
            "testName": "Google Meet Basic - Web11",
            "savedEvent": False,
            "type": "page-load",
            "alertsEnabled": True,
            "enabled": True,
            "url": "https://meet.google.com",
            "authType": "none",
            "bandwidthMeasurements": False,
            "httpTargetTime": 1000,
            "httpTimeLimit": 5,
            "httpVersion": 2,
            "includeHeaders": True,
            "mtuMeasurements": True,
            "numPathTraces": 3,
            "pathTraceMode": "classic",
            "probeMode": "auto",
            "networkMeasurements": True,
            "protocol": "tcp",
            "sslVersionId": "0",
            "useNtlm": False,
            "verifyCertificate": True,
            "allowUnsafeLegacyRenegotiation": True,
            "overrideAgentProxy": False,
            "distributedTracing": False,
            "allowGeolocation": False,
            "allowMicAndCamera": False,
            "blockDomains": "",
            "browserLanguage": "en-US",
            "disableScreenshot": False,
            "pageLoadingStrategy": "normal",
            "contentRegex": "",
            "emulatedDeviceId": "281474976710656",
            "followRedirects": True,
            "pageLoadTargetTime": 6,
            "pageLoadTimeLimit": 10,
            "randomizedStartTime": False,
            "sslVersion": "Auto",
            "agents": [{"agentId": "4739"}]
        }
        ]
    return tests