def create_http_tests(agent_list):
    tests = [
            {
            "interval": 900,
            "bgpMeasurements": True,
            "usePublicBgp": True,
            "liveShare": False,
            "testName": "M365 Basic - OneDrive - Web - External",
            "savedEvent": False,
            "type": "http-server",
            "alertsEnabled": True,
            "enabled": True,
            "url": "https://elisacorporation.sharepoint.com",
            "authType": "none",
            "bandwidthMeasurements": False,
            "httpTargetTime": 1000,
            "httpTimeLimit": 5,
            "httpVersion": 2,
            "mtuMeasurements": True,
            "numPathTraces": 3,
            "pathTraceMode": "classic",
            "probeMode": "auto",
            "networkMeasurements": True,
            "protocol": "tcp",
            "sslVersionId": "0",
            "useNtlm": False,
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/80.0.100.0",
            "verifyCertificate": True,
            "allowUnsafeLegacyRenegotiation": True,
            "overrideAgentProxy": False,
            "collectProxyNetworkData": False,
            "distributedTracing": False,
            "contentRegex": "",
            "followRedirects": False,
            "ipv6Policy": "use-agent-policy",
            "randomizedStartTime": False,
            "sslVersion": "Auto",
            "agents": [{"agentId": "4739"}]
        },
        
        {
            "interval": 900,
            "bgpMeasurements": True,
            "usePublicBgp": True,
            "liveShare": False,
            "testName": "M365 Basic - SharePoint - Web - External",
            "savedEvent": False,
            "type": "http-server",
            "alertsEnabled": True,
            "enabled": True,
            "url": "https://elisacorporation.sharepoint.com",
            "authType": "none",
            "bandwidthMeasurements": False,
            "httpTargetTime": 1000,
            "httpTimeLimit": 5,
            "httpVersion": 2,
            "mtuMeasurements": True,
            "numPathTraces": 3,
            "pathTraceMode": "classic",
            "probeMode": "auto",
            "networkMeasurements": True,
            "protocol": "tcp",
            "sslVersionId": "0",
            "useNtlm": False,
            "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/80.0.100.0",
            "verifyCertificate": True,
            "allowUnsafeLegacyRenegotiation": True,
            "overrideAgentProxy": False,
            "collectProxyNetworkData": False,
            "distributedTracing": False,
            "contentRegex": "",
            "followRedirects": False,
            "ipv6Policy": "use-agent-policy",
            "randomizedStartTime": False,
            "sslVersion": "Auto",
            "agents": [{"agentId": "4739"}]
        },
        {
            "interval": 900,
            "bgpMeasurements": True,
            "usePublicBgp": True,
            "liveShare": False,
            "testName": "MSTeams - Login - Web - External",
            "savedEvent": False,
            "type": "http-server",
            "alertsEnabled": True,
            "enabled": True,
            "url": "https://login.microsoftonline.com",
            "authType": "none",
            "bandwidthMeasurements": False,
            "httpTargetTime": 1000,
            "httpTimeLimit": 5,
            "httpVersion": 2,
            "mtuMeasurements": True,
            "numPathTraces": 3,
            "pathTraceMode": "classic",
            "probeMode": "auto",
            "networkMeasurements": True,
            "protocol": "tcp",
            "sslVersionId": "0",
            "useNtlm": False,
            "verifyCertificate": True,
            "allowUnsafeLegacyRenegotiation": True,
            "overrideAgentProxy": False,
            "collectProxyNetworkData": False,
            "distributedTracing": False,
            "contentRegex": "",
            "followRedirects": True,
            "ipv6Policy": "use-agent-policy",
            "randomizedStartTime": False,
            "sslVersion": "Auto",
			"agents": [{"agentId": "4739"}]
        }
        ]
    return tests