def create_agent_tests(agent_list):
    tests = [
            {
    
            "interval": 900,
            "bgpMeasurements": True,
            "usePublicBgp": True,
            "liveShare": False,
            "testName": "MSTeams - MS Teams (Audio) - External11",
			"savedEvent": False,
            "type": "agent-to-server",
            "alertsEnabled": True,
            "enabled": True,
            "bandwidthMeasurements": False,
            "continuousMode": False,
            "dscpId": "46",
            "ipv6Policy": "use-agent-policy",
            "mtuMeasurements": True,
            "numPathTraces": 3,
            "pathTraceMode": "classic",
            "probeMode": "auto",
            "networkMeasurements": True,
            "protocol": "tcp",
            "randomizedStartTime": False,
            "server": "teams.microsoft.com",
            "dscp": "EF (DSCP 46)",
            "agents": [{"agentId": "4739"}]
        },
        {
            "interval": 900,
            "bgpMeasurements": True,
            "usePublicBgp": True,
            "liveShare": False,
            "testName": "MSTeams - MS Teams (Video) - External11",
			"savedEvent": False,
            "type": "agent-to-server",
            "alertsEnabled": True,
            "enabled": True,
            "bandwidthMeasurements": False,
            "continuousMode": False,
            "dscpId": "34",
            "ipv6Policy": "use-agent-policy",
            "mtuMeasurements": True,
            "numPathTraces": 3,
            "pathTraceMode": "classic",
            "probeMode": "auto",
            "networkMeasurements": True,
            "protocol": "tcp",
            "randomizedStartTime": False,
            "server": "teams.microsoft.com",
            "dscp": "AF 41 (DSCP 34)",
             "agents": [{"agentId": "4739"}]
        },
        {
            "interval": 900,
            "bgpMeasurements": True,
            "usePublicBgp": True,
            "liveShare": False,
            "testName": "MSTeams - MS Teams TR - External11",
            "savedEvent": False,
            "type": "agent-to-server",
            "alertsEnabled": True,
            "enabled": True,
            "bandwidthMeasurements": False,
            "continuousMode": False,
            "dscpId": "0",
            "ipv6Policy": "use-agent-policy",
            "mtuMeasurements": True,
            "numPathTraces": 3,
            "pathTraceMode": "classic",
            "probeMode": "auto",
            "networkMeasurements": True,
            "protocol": "tcp",
            "randomizedStartTime": False,
            "server": "teams.microsoft.com",
            "dscp": "Best Effort (DSCP 0)",
             "agents": [{"agentId": "4739"}]
        }
          
            
        ]
    return tests